function design(data){
    if(data == '*')
    console.log("***")
    else if(data == '$')
    console.log("$$$$$$$$$$$$$")
    else if(data == '.')
    console.log(".............")
    else if(data == '-')
    console.log("-------------")
}
design('*')
console.log("hi")
design('-')
console.log("hello")
design('$')